import React from 'react';
// import Link from 'next/link';


export const metadata = {
          title: "Welcome to product page",
          description: "Generated by create next app",
        };




const page = () => {
    
 

  return (
   <div>
    <h1>products</h1>
   </div>
  );
};

export default page;
